# We don't build in Travis, we build in Docker, so no language support is needed 
language: generic

services: docker

script: 
  - |
    docker build --rm \
    -t cadg:test \
    -f ./test/Dockerfile \
    .
  - docker build --rm -t cadg-rest-server:test -f ./rest-server/Dockerfile ./rest-server/
