version: "3"
services:
        apache:
                build: ../docker-cadg-apache
                ports:
                        - "8080:80"
                        - "8443:443"
                depends_on:
                        - "cadg-rest"
                        - "cadg-ui"
                networks:
                        - cadgnet
                volumes:
                        - "react-app:/usr/local/apache2/htdocs"
        cadg-rest:
                build: ../rest-server/
                tty: true
                networks:
                        - cadgnet
                depends_on:
                        - "cadg-db"
                environment:
                        - DB_ADMIN_NAME=${DB_ADMIN_NAME}
                        - DB_ADMIN_TABLE=${DB_ADMIN_TABLE}
                        - DB_ALERT_TABLE=${DB_ALERT_TABLE}
                        - DB_CADG_NAME=${DB_CADG_NAME}
                        - DB_DISSEMINATOR_TABLE=${DB_DISSEMINATOR_TABLE}
                        - DB_PASSWORD=${DB_PASSWORD}
                        - DB_PORT=${DB_PORT}
                        - DB_SERVER=${DB_SERVER}
                        - DB_UID=${DB_UID}
        cadg-soap:
                build: ../soap-server/
                networks:
                        - cadgnet
        cadg-db:
                build: ../cadg-db
                networks:
                        - cadgnet
        cadg-ui:
                build: ../cadg-ui
                volumes:
                        - "react-app:/cadg-ui/build"
networks:
        cadgnet:
volumes:
        react-app:
