version: "3"
services:
        apache:
                build: ../docker-cadg-apache
                ports:
                        - "8080:80"
                depends_on:
                  - "cadg-rest"
                networks:
                        - cadgnet
        cadg-rest:
                build: ../rest-server/
                tty: true
                networks:
                        - cadgnet
        cadg-db:
                build: ../cadg-db
                networks:
                        - cadgnet
                command: mysql -p='' < create_cadg_db.sql
                environment:
                        MYSQL_ROOT_PASSWORD: example
networks:
        cadgnet:
