version: "3"
services:
        apache:
                build: ../docker-cadg-apache
                ports:
                        - "8080:80"
                depends_on:
                        - "cadg-rest"
                networks:
                        - cadgnet
        cadg-rest:
                build: ../rest-server/
                tty: true
                networks:
                        - cadgnet
                depends_on:
                        - "cadg-db"
                environment:
                        - DB_PASSWORD=${DB_PASSWORD}
        cadg-db:
                build: ../cadg-db
                networks:
                        - cadgnet
networks:
        cadgnet:
